export const USER_ACTIONS = {
  SET_USER: 'SET_USER',
  SET_LOADING: 'SET_LOADING',
  LOGOUT: 'LOGOUT'
};

export const ACTIVITY_ACTIONS = {
  SET_ACTIVITIES: 'SET_ACTIVITIES',
  ADD_ACTIVITY: 'ADD_ACTIVITY',
  SET_FILTERS: 'SET_FILTERS'
};

export const PROGRESS_ACTIONS = {
  UPDATE_PROGRESS: 'UPDATE_PROGRESS',
  RESET_PROGRESS: 'RESET_PROGRESS'
};